version: "2.4"

services:
  sbc:
    image: apyos/docker-3cx-sbc
    network_mode: host
    restart: unless-stopped
    environment:
      - PBX_URL=https://my.3cx.be
      - PBX_KEY=MySBCKey
      - WATCHTOWER_API=127.0.0.1:8123
      - WATCHTOWER_TOKEN=token
    labels:
      - "com.centurylinklabs.watchtower.scope=3cxsbc"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api-update
    ports:
      - 127.0.0.1:8123:8080
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=token
    labels:
      - "com.centurylinklabs.watchtower.scope=3cxsbc"
